~name: Drift Detection and Reconciliation

on:
  schedule:
    - cron:  '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  detect-and-reconcile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: steps.plan.outputs.stdout && !contains(steps.plan.outputs.stdout, 'No changes')
        run: terraform apply -auto-approve tfplan
~
